language: php
php:
  - '5.6'
  - '7.1'
git:
  depth: 1
install: 
  - composer install --no-interaction --no-suggest
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - phpunit
  - npm run build
  - npm test
cache:
  directories:
  - node_modules
  - $HOME/.cache/composer
